/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef fetch_URL_H
#define fetch_URL_H

#include <thrift/TDispatchProcessor.h>
#include "HTTPProxy_types.h"

namespace HTTP_ProxyServer {

class fetch_URLIf {
 public:
  virtual ~fetch_URLIf() {}
  virtual void get(HTTP_Proxy& _return, const std::string& URL) = 0;
};

class fetch_URLIfFactory {
 public:
  typedef fetch_URLIf Handler;

  virtual ~fetch_URLIfFactory() {}

  virtual fetch_URLIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(fetch_URLIf* /* handler */) = 0;
};

class fetch_URLIfSingletonFactory : virtual public fetch_URLIfFactory {
 public:
  fetch_URLIfSingletonFactory(const boost::shared_ptr<fetch_URLIf>& iface) : iface_(iface) {}
  virtual ~fetch_URLIfSingletonFactory() {}

  virtual fetch_URLIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(fetch_URLIf* /* handler */) {}

 protected:
  boost::shared_ptr<fetch_URLIf> iface_;
};

class fetch_URLNull : virtual public fetch_URLIf {
 public:
  virtual ~fetch_URLNull() {}
  void get(HTTP_Proxy& /* _return */, const std::string& /* URL */) {
    return;
  }
};

typedef struct _fetch_URL_get_args__isset {
  _fetch_URL_get_args__isset() : URL(false) {}
  bool URL;
} _fetch_URL_get_args__isset;

class fetch_URL_get_args {
 public:

  fetch_URL_get_args() : URL() {
  }

  virtual ~fetch_URL_get_args() throw() {}

  std::string URL;

  _fetch_URL_get_args__isset __isset;

  void __set_URL(const std::string& val) {
    URL = val;
  }

  bool operator == (const fetch_URL_get_args & rhs) const
  {
    if (!(URL == rhs.URL))
      return false;
    return true;
  }
  bool operator != (const fetch_URL_get_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const fetch_URL_get_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class fetch_URL_get_pargs {
 public:


  virtual ~fetch_URL_get_pargs() throw() {}

  const std::string* URL;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _fetch_URL_get_result__isset {
  _fetch_URL_get_result__isset() : success(false) {}
  bool success;
} _fetch_URL_get_result__isset;

class fetch_URL_get_result {
 public:

  fetch_URL_get_result() {
  }

  virtual ~fetch_URL_get_result() throw() {}

  HTTP_Proxy success;

  _fetch_URL_get_result__isset __isset;

  void __set_success(const HTTP_Proxy& val) {
    success = val;
  }

  bool operator == (const fetch_URL_get_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const fetch_URL_get_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const fetch_URL_get_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _fetch_URL_get_presult__isset {
  _fetch_URL_get_presult__isset() : success(false) {}
  bool success;
} _fetch_URL_get_presult__isset;

class fetch_URL_get_presult {
 public:


  virtual ~fetch_URL_get_presult() throw() {}

  HTTP_Proxy* success;

  _fetch_URL_get_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class fetch_URLClient : virtual public fetch_URLIf {
 public:
  fetch_URLClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  fetch_URLClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void get(HTTP_Proxy& _return, const std::string& URL);
  void send_get(const std::string& URL);
  void recv_get(HTTP_Proxy& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class fetch_URLProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<fetch_URLIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (fetch_URLProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_get(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  fetch_URLProcessor(boost::shared_ptr<fetch_URLIf> iface) :
    iface_(iface) {
    processMap_["get"] = &fetch_URLProcessor::process_get;
  }

  virtual ~fetch_URLProcessor() {}
};

class fetch_URLProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  fetch_URLProcessorFactory(const ::boost::shared_ptr< fetch_URLIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< fetch_URLIfFactory > handlerFactory_;
};

class fetch_URLMultiface : virtual public fetch_URLIf {
 public:
  fetch_URLMultiface(std::vector<boost::shared_ptr<fetch_URLIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~fetch_URLMultiface() {}
 protected:
  std::vector<boost::shared_ptr<fetch_URLIf> > ifaces_;
  fetch_URLMultiface() {}
  void add(boost::shared_ptr<fetch_URLIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void get(HTTP_Proxy& _return, const std::string& URL) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->get(_return, URL);
    }
    ifaces_[i]->get(_return, URL);
    return;
  }

};

} // namespace

#endif
