// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "fetch_URL.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::HTTP_Proxy;

class fetch_URLHandler : virtual public fetch_URLIf {
 public:
  fetch_URLHandler() {
    // Your initialization goes here
  }

  void get(HTTP_Proxy& _return, const std::string& URL) {
    // Your implementation goes here
    printf("get\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<fetch_URLHandler> handler(new fetch_URLHandler());
  shared_ptr<TProcessor> processor(new fetch_URLProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

