/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef HTTPProxy_TYPES_H
#define HTTPProxy_TYPES_H

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/cxxfunctional.h>


namespace HTTP_Proxy {

typedef struct _HTTP_Proxy__isset {
  _HTTP_Proxy__isset() : URL(false) {}
  bool URL;
} _HTTP_Proxy__isset;

class HTTP_Proxy {
 public:

  static const char* ascii_fingerprint; // = "5EA2D527ECA3BA20C77AFC023EE8C05F";
  static const uint8_t binary_fingerprint[16]; // = {0x5E,0xA2,0xD5,0x27,0xEC,0xA3,0xBA,0x20,0xC7,0x7A,0xFC,0x02,0x3E,0xE8,0xC0,0x5F};

  HTTP_Proxy() {
  }

  virtual ~HTTP_Proxy() throw() {}

  std::map<std::string, std::string>  URL;

  _HTTP_Proxy__isset __isset;

  void __set_URL(const std::map<std::string, std::string> & val) {
    URL = val;
  }

  bool operator == (const HTTP_Proxy & rhs) const
  {
    if (!(URL == rhs.URL))
      return false;
    return true;
  }
  bool operator != (const HTTP_Proxy &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const HTTP_Proxy & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

void swap(HTTP_Proxy &a, HTTP_Proxy &b);

} // namespace

#endif
