/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "HTTPProxy_constants.h"

namespace HTTP_Proxy {

const HTTPProxyConstants g_HTTPProxy_constants;

HTTPProxyConstants::HTTPProxyConstants() {
}

} // namespace

