/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef HTTPProxy_CONSTANTS_H
#define HTTPProxy_CONSTANTS_H

#include "HTTPProxy_types.h"

namespace HTTP_Proxy {

class HTTPProxyConstants {
 public:
  HTTPProxyConstants();

};

extern const HTTPProxyConstants g_HTTPProxy_constants;

} // namespace

#endif
