/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef TimeServer_CONSTANTS_H
#define TimeServer_CONSTANTS_H

#include "TimeServer_types.h"

namespace TimeServer {

class TimeServerConstants {
 public:
  TimeServerConstants();

};

extern const TimeServerConstants g_TimeServer_constants;

} // namespace

#endif
