/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "TimeServer_constants.h"

namespace TimeServer {

const TimeServerConstants g_TimeServer_constants;

TimeServerConstants::TimeServerConstants() {
}

} // namespace

