/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ProxyServer_TYPES_H
#define ProxyServer_TYPES_H

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/cxxfunctional.h>


namespace HTTP_Server {

typedef struct _HTTPServer__isset {
  _HTTPServer__isset() : url_Body(false) {}
  bool url_Body;
} _HTTPServer__isset;

class HTTPServer {
 public:

  static const char* ascii_fingerprint; // = "5EA2D527ECA3BA20C77AFC023EE8C05F";
  static const uint8_t binary_fingerprint[16]; // = {0x5E,0xA2,0xD5,0x27,0xEC,0xA3,0xBA,0x20,0xC7,0x7A,0xFC,0x02,0x3E,0xE8,0xC0,0x5F};

  HTTPServer() {
  }

  virtual ~HTTPServer() throw() {}

  std::map<std::string, std::string>  url_Body;

  _HTTPServer__isset __isset;

  void __set_url_Body(const std::map<std::string, std::string> & val) {
    url_Body = val;
  }

  bool operator == (const HTTPServer & rhs) const
  {
    if (!(url_Body == rhs.url_Body))
      return false;
    return true;
  }
  bool operator != (const HTTPServer &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const HTTPServer & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

void swap(HTTPServer &a, HTTPServer &b);

} // namespace

#endif
